### ISSUE TITLE
Change tagged person for the 'good first issues' label

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppiabot#164]
Instead of tagging Showtime3, Oppiabot should tag DubeySandeep when someone assigns the 'good first issue' tag https://github.com/oppia/oppia/issues/11313#issuecomment-737695429

### TODO

- [ ] Replace Showtime3 with DubeySandeep in the comment
- [ ] Find other mentions of Showtim3 in the oppiabot codebase and replace him with appropriate person
- [ ] When some person is included in a comment preferably allow configuring that person in https://github.com/oppia/oppiabot/blob/master/userWhitelist.json
